<?php

namespace App\Models;

use App\Observers\NewsS9Observer;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Log;

class News_s9 extends Model
{
    protected $table = 'news_table_s9';
    use HasFactory;
    protected $fillable = [
        'title'
    ];

    protected static function boot()
    {
        parent::boot();

        // Регистрируем Observer вручную
        static::observe(NewsS9Observer::class);
    }

    // protected static function boot()
    // {
    //     parent::boot(); // TODO: Change the autogenerated stub

    //     static::updating(function (News_s9 $news) {
    //         Log::info('Updating news' . $news);
    //     });
    // }
}
